### ISSUE TITLE
ポストのタイトルがファイル名になってしまう

### ISSUE THREAD

**Issue by chaspy** [jdd-ug/jdd-ug.github.io#10]
ページの H1 タイトルがファイル名になってしまう。そのため、タイトルが日本語だと url も日本語になる。パーセントエンコーディングされた urlになって見栄えが悪いのと長い。

**Comment by IchiroKano** [comment]
### WEB検索で見つからなかったけれど、Copilotに聞いてみた。あとで試そう

1. ファイル名を英語に設定: 各投稿やページのファイル名を英語で作成します。例えば、my-post.mdのようにします。
2. フロントマターでタイトルを設定:各投稿やページの冒頭にあるフロントマターで、日本語のタイトルを設定します。例えば：

```
---
title: "日本語のタイトル"
---
```

3. パーマリンクをカスタマイズ: _config.ymlファイルでパーマリンクの設定をカスタマイズします。例えば、以下のように設定することで、ファイル名をURLに反映させることができます：
```
permalink: /:categories/:year/:month/:day/:title/
```

これにより、ファイル名は英語のまま、日本語のタイトルを表示することができます。試してみてください！他に質問があれば教えてください。
