### ISSUE TITLE
Jekyll の プラグインで Site Map 作る

### ISSUE THREAD

**Issue by IchiroKano** [jdd-ug/jdd-ug.github.io#2]
タイトルの通り、自動で sitemap.xml を生成できそうなのでいつかやる。

**Comment by IchiroKano** [comment]
@chaspy 
サイトマップが自動生成されています。設定してくれたのでしょうか？
https://jdd-ug.github.io/sitemap.xml

**Comment by chaspy** [comment]
いえ、おそらくこの gem によるものな気がしますね。
https://github.com/jdd-ug/jdd-ug.github.io/blob/main/Gemfile#L19

**Comment by IchiroKano** [comment]
sitemapのプラグイン、入っていますね。
Google Search に登録しました。

```
サイトマップ	型	送信	最終読み込み日時	ステータス	検出されたページ数	検出された動画数	
/sitemap.xml	サイトマップ	2024/08/19	2024/08/19	成功しました	13	
```
