### ISSUE TITLE
プレビュー環境が欲しい

### ISSUE THREAD

**Issue by chaspy** [jdd-ug/jdd-ug.github.io#8]
ローカルでビルドすれば確認はできるかもしれないが、ホストされた形で確認もしたい。

**Comment by IchiroKano** [comment]
もしVScodeでmdファイルを生成していたら、ターミナルで  `> jekyll serve` を実行するとローカルWEBサーバーが起動します。
WEBサーバーが起動したら、http: //127.0.0.1:4000/ でプレビューできます。あとはmdを更新するとすぐにブラウザをリロードするだけ。

https://jekyllrb-ja.github.io/docs/

**Comment by chaspy** [comment]
とりあえず二人だし local 環境で凌ぐとします。README に追記しておきます。
